### ISSUE TITLE
Static problem size

### ISSUE THREAD

**Issue by DerAlbiG** [Rookfighter/least-squares-cpp#4]
Hi, thank you for the wonderful library.
For use in microcontrollers, a possibility to set the problem size via template parameter would be awesome. This should avoid dynamic memory allocations and therefore speed up the algorithm significantly. (Even on X86/X64.)

This should also give better optimization potential when unrolling loops etc.

**Comment by Rookfighter** [comment]
Fixed size problems are now implemented.
