### ISSUE TITLE
Question: In LSQAlgorithm, why subtract the step result to xval? 

### ISSUE THREAD

**Issue by HollowSun0** [Rookfighter/least-squares-cpp#6]
On line https://github.com/Rookfighter/least-squares-cpp/blob/master/include/lsqcpp.h#L875, why are we subtracting the resulting step to xval?

If I understand correctly, starting from coordinate xval, step points to the new xval for the optimizer to use on the next iteration?

Maybe I'm missing something here...

Thank you,
Patrick

**Comment by HollowSun0** [comment]
Nevermind. The backtracking updates using "xvalN = xval - stepSize * step;". As long as both are consistent, it should be ok

**Comment by Rookfighter** [comment]
Hi HollowSun0,

You are right in literature the step is sometimes adds the step to the current state estimate. But they use the negative gradient to calculate the step. As you say, as long as we stay consistent, it is equivalent the two methods are equivalent:
- calculate the step with **negative** gradient and **add** it to the state estimate
- calculate tge step with **positive** gradient and **subtract** it from the state estimate
